### ISSUE TITLE
coc-java-debug for tomcat7 in docker

### ISSUE THREAD

**Issue by fedoranvar** [dansomething/coc-java-debug#8]
Good day to you!

I have java spring application that runs in docker-container (tomcat7) and I want to debug it from vim.

here is my docker-compose.yml for java app :
```yaml
version: '3'
services:
    java-tomcat:
        build:
            context: ../_bin/${JAVA_VERSION}
        container_name: "${CONTAINER_NAME}"
        restart: always
        volumes:
          - ${DOCUMENT_ROOT}/WAR:/usr/local/tomcat/webapps/
          - ${TOMCAT_CONF}:/usr/local/tomcat/conf/
        environment:
              ENV JPDA_ADDRESS: "8000"
              ENV JPDA_TRANSPORT: "dt_socket"
        networks: 
            - lamp
        ports:
            - 8888:8080
            - 9000:8000
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.${CONTAINER_NAME}.rule=Host(`${CONTAINER_NAME}.docker.localhost`)"
          - "traeeik.http.routers.${CONTAINER_NAME}.entrypoints=web"

networks:
    lamp:
        external: true
```
my .vimspector.json:
```json
{
  "adapters": {
    "java-debug-server": {
      "name": "vscode-java",
      "port": "${AdapterPort}"
      }
  },
  "configurations": {
    "Java Attach": {
      "adapter": "java-debug-server",
      "configuration": {
        "request": "attach",
        "host": "localhost",
        "port": "5005"
      },
      "breakpoints": {
        "exception": {
          "caught": "N",
          "uncaught": "N"
        }
      }
    }
  }
}

```
after container runs I'm calling 
`:CocCommand java.debug.vimspector.start`
and 
m
after that it loads hangs in 'Attaching in debugee...'
![image](https://user-images.githubusercontent.com/52028706/90501336-adad8c80-e165-11ea-98aa-5d319bc93f7d.png)

Before that I've had a problem with running java server and it was resolved by using answer:
https://github.com/neoclide/coc-java/issues/99#issuecomment-663856695

My thoughts, that I have incorrect .vimspector.json config, but at the moment can't figure out what to do.
Will appreciate any help!

Thanks!
